FROM sipster-gcc4.9
MAINTAINER KINOSHITA minoru <5021543+minoruta@users.noreply.github.com>

ARG VERSION_PJSIP=2.7.2
ARG VERSION_LIBSRTP=2.1.0

#
#   Prepare requirments
#
RUN apt -qq update \
&&  apt -qq install -y \
        wget \
&&  apt-get clean \
&&  rm -rf /var/lib/apt/lists/*

#
#   Prepare strp for pjsip
#
WORKDIR /root
RUN wget https://github.com/cisco/libsrtp/archive/v$VERSION_LIBSRTP.tar.gz \
&&  tar xzf v$VERSION_LIBSRTP.tar.gz \
&&  rm v$VERSION_LIBSRTP.tar.gz \
&&  cd libsrtp-$VERSION_LIBSRTP \
&&  ./configure > /dev/null \
&&  make \
&&  make install \
&&  make clean \
&&  ldconfig \
&&  cd ..

#
#   Prepare PJSIP
#
RUN wget -nv "http://www.pjsip.org/release/$VERSION_PJSIP/pjproject-$VERSION_PJSIP.tar.bz2" -O - | tar xjf - \
&&  cd pjproject-$VERSION_PJSIP \
&&  ./configure \
  --with-external-srtp  \
  --enable-shared \
  --disable-sound \
  --disable-oss \
  --disable-sdl \
  --disable-speex-aec \
  --disable-video \
  > /dev/null \
&& make dep all \
&& make install \
&& make clean \
&& ldconfig
