FROM ubuntu:14.04
MAINTAINER KINOSHITA minoru <5021543+minoruta@users.noreply.github.com>

#
#   Install GCC4.9
#
RUN apt -qq update \
&&  apt -qq install -y software-properties-common \
&&  add-apt-repository ppa:ubuntu-toolchain-r/test \
&&  apt -qq update \
&&  apt -qq install -y \
        pkg-config \
        build-essential \
        gcc-4.9 \
        g++-4.9 \
&&  apt-get clean \
&&  rm -rf /var/lib/apt/lists/* \
&&  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
